Models/MyToDoList.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TODOAPP_DOTNETCOREMVC.Models
{
    public class MyToDoList
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Controllers/MyToDoListController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TODOAPP_DOTNETCOREMVC.Models;
using TODOAPP_DOTNETCOREMVC.Models.AppRepository;
using TODOAPP_DOTNETCOREMVC.ViewModels;

namespace TODOAPP_DOTNETCOREMVC.Controllers
{
    public class MyToDoListController : Controller
    {

        public IMyTodoListRepository<MyToDoList> myTodoListRepository { get; }
        public IMyTodoListRepository<MyTodoTask> myTasksRepository { get; }

        public MyToDoListController(IMyTodoListRepository<MyToDoList> _myTodoListRepository,
                                    IMyTodoListRepository<MyTodoTask> _myListTasksRepository)
        {
            myTodoListRepository = _myTodoListRepository;
            myTasksRepository = _myListTasksRepository;
        }
        [HttpGet]
        [Route("/")]
        public IActionResult Index(int? id)
        {
            if (id != null)
            {
                var ToDoLists = myTodoListRepository.List();
                if (ToDoLists.SingleOrDefault(l => l.Id == id) == null)
                {
                    return View();
                }
                var SelectedListTasks = myTasksRepository.List().Where(t => t.TodoListId == id).ToList();
                var SelectdTodoList = new ListDetailsViewModel {
                    SelectedListId = (int)id,
                    AllLists = ToDoLists,
                    AllListTasks = SelectedListTasks };
                return View(SelectdTodoList);
            }
            return View(getAllOrNull());
        }


        [HttpPost]
        public IActionResult AddToDoList(string newList)
        {
            if (newList == null)
            {
                return RedirectToAction("Index");
            }
            myTodoListRepository.Add(new MyToDoList { Name = newList });
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult AddTaskToList(int? ListId, string NewTask)
        {
            if (string.IsNullOrEmpty(NewTask) || ListId == null || NewTask.Count() < 1)
            {
                return RedirectToAction("Index");
            }

            var newTask = new MyTodoTask {
                TaskDetails = NewTask,
                TodoListId = (int)ListId
            };
            myTasksRepository.Add(newTask);
            return RedirectToAction("Index", new { id = ListId });
        }

        public IActionResult DeleteTask(int? ListId,int? TaskId)
        {
            if (ListId == null || TaskId == null)
            {
                RedirectToAction("Index");
            }
            myTasksRepository.Delete((int)TaskId);

            return RedirectToAction("Index", new { id = ListId });
        }

        public IActionResult DeleteList(int? ListId)
        {
            if (ListId == null)
            {
                RedirectToAction("Index");
            }
            myTodoListRepository.Delete((int)ListId);
            foreach (var myTask in myTasksRepository.List())
            {
                if (myTask.TodoListId == ListId)
                {
                    myTasksRepository.Delete(myTask.Id);
                }
            }

            return RedirectToAction("Index");
        }

        public ListDetailsViewModel getAllOrNull()
        {
            var allToDoLists = myTodoListRepository.List();
            var SelectedToDoList = allToDoLists.SingleOrDefault(listId => listId.Id == allToDoLists.Max(l => l.Id));
            if (SelectedToDoList == null)
            {
                return null;
            }
            var defaultSelectedListTasks = myTasksRepository.List().Where(t => t.TodoListId == SelectedToDoList.Id).ToList() ?? new List<MyTodoTask>();
            if (allToDoLists.Count == 0 || SelectedToDoList == null)
            {
                return null;
            }
            return new ListDetailsViewModel { SelectedListId = allToDoLists.Min(l => l.Id), AllLists = allToDoLists, AllListTasks = defaultSelectedListTasks };
        }
    }
}

Views/MyToDoList/Index.cshtml
@model TODOAPP_DOTNETCOREMVC.ViewModels.ListDetailsViewModel
@{
    Layout = "_Layout";
    ViewData["Title"] = "My TODO List";
    string selectedTaskTitle = null;
    if (Model != null)
    {
        selectedTaskTitle = Model.AllLists.SingleOrDefault(l => l.Id == Model.SelectedListId).Name;
    }
}

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<div class="col-md-12 row" style="margin-top:100px">
    <span class="text-white text-start display-6 col-12 mb-4">My lists</span>
    @if (Model != null)
    {
        <div class="col-md-4">
            <div class="">
                @foreach (var taskList in Model.AllLists)
                {
                    <div class="w-100 d-inline-block m-2 row">
                        <a class="text-white w-100 d-inline-block todo-list"
                           href="?id=@taskList.Id">
                            <i class="far fa-circle"></i>&nbsp;&nbsp;@taskList.Name
                        </a>
                    </div>
                }

            </div>
        </div>
        <div class="col-md-8 bg-white" style="border-radius: 3px;">
            <div class="row tasks-div border">
                @if (selectedTaskTitle != null)
                {
                    <div class="text-start tasks-header col-md-6 my-auto ps-5">
                        <span>@selectedTaskTitle</span>
                    </div>
                    <div class="text-end col-md-6 my-auto pe-5" style="color: #4e4e4e; ">
                        <span></span>
                    </div>
                }
            </div>
            <div class="mt-4 row">
                @if (Model.AllListTasks.Count > 0)
                {

                    @foreach (var taskitem in Model.AllListTasks)
                    {
                        <div class="w-100 py-1 row">
                            <div class="col-md-8">
                                <a class="task-item" href="#">
                                    <i class="far fa-circle"></i>&nbsp;&nbsp;@taskitem.TaskDetails
                                </a>
                            </div>
                            <form class="col-md-4 text-end" asp-controller="MyToDoList" asp-action="DeleteTask" method="post">
                                <button class="task-item btn btn-danger bg-white text-danger border-light" type="submit">
                                    <i class="fas fa-eraser"></i>
                                </button>
                                <input name="ListId" value="@Model.SelectedListId" hidden />
                                <input name="TaskId" value="@taskitem.Id" hidden />
                            </form>
                        </div>
                    }
                }
                else
                {
                    <div class="alert-danger p-4 display-6 w-100">No Task in this list !</div>
                }
            </div>
            <div class="col-md-12 row my-4">
                <label class="my-auto text-info col-2 newtaskinputlabel" for="newtaskinput"><i class="fas fa-plus"></i></label>
                <form class="col-md-10" asp-controller="MyToDoList" asp-action="AddTaskToList" method="post">
                    <input class="new-task-input w-100" name="ListId" type="hidden" value="@Model.SelectedListId" />
                    <input class="new-task-input w-100" name="NewTask" id="newtaskinput" type="text" />
                </form>
            </div>
        </div>
        <div class="col-md-12 row mt-4">
            <div class="col-md-4"></div>
            <div class="col-md-8 row">
                <div class="col-md-6 text-start">
                </div>
                <form class="col-md-6 text-end" asp-action="DeleteList" method="post">
                    <button type="submit" class="actionbtns btn btn-light">Delete List</button>
                    <input name="ListId" value="@Model.SelectedListId" hidden />
                </form>
            </div>
        </div>
    }
    else
    {
        <span class="text-sm-start alert-danger p-4 display-6">No TODO List is available</span>
    }
</div>
<div class="col-md-4 add-list row ps-2">
    <label class="my-auto col-1 newlistinputlabel" for="newlistinput"><i class="fas fa-plus"></i></label>
    <form class="col-md-11" asp-controller="MyToDoList" asp-action="AddToDoList" method="post">
        <input name="newList" class="new-list-input w-100" id="newlistinput" type="text" />
    </form>
</div>